version: 3

tasks:
  list-boards:
    cmds:
      - arduino-cli board list

  compile-requirements:
    desc: Compile requirements.in to requirements.txt
    sources:
        - requirements.in
    cmds:
      - pip-compile -o requirements.txt
  install-requirements:
    desc: Install or update python packages using requirements.txt
    deps:
      - compile-requirements
    sources:
      - requirements.txt
    cmds:
      - pip install -r requirements.txt
  test:
    desc: Run tests
    cmds:
      - pytest -v --cov=src --cov-report=term-missing --cov-fail-under=75 src/
  benchmark-serial-local:
    desc: Run benchmark for serial processing and local inputs and outputs
    cmds:
      - benchmarks serial IMG_3134.jpeg crops.csv results/ -r 20 -rm
  benchmark-serial-remote:
    desc: Run benchmark for serial processing and remote inputs and outputs
    cmds:
      - benchmarks serial gs://akuc-machine-learning-vertex-ai-pipelines-bucket/IMG_3134.jpeg gs://akuc-machine-learning-vertex-ai-pipelines-bucket/crops.csv  gs://akuc-machine-learning-vertex-ai-pipelines-bucket/io-tests/results -r 20 -rm
  benchmark-async-local:
    desc: Run benchmark for async processing and local inputs and outputs
    cmds:
      - benchmarks asynchronous IMG_3134.jpeg crops.csv results/ -r 20 -rm
  benchmark-async-remote:
    desc: Run benchmark for async processing and remote inputs and outputs
    cmds:
      - benchmarks asynchronous gs://akuc-machine-learning-vertex-ai-pipelines-bucket/IMG_3134.jpeg gs://akuc-machine-learning-vertex-ai-pipelines-bucket/crops.csv  gs://akuc-machine-learning-vertex-ai-pipelines-bucket/io-tests/results -r 20 -rm
  benchmark-multithread-local:
    desc: Run benchmark for multithread processing and local inputs and outputs
    cmds:
      - benchmarks multithreading IMG_3134.jpeg crops.csv results/ -r 20 -rm -e thread
  benchmark-multithread-remote:
    desc: Run benchmark for multithread processing and remote inputs and outputs
    cmds:
      - benchmarks multithreading gs://akuc-machine-learning-vertex-ai-pipelines-bucket/IMG_3134.jpeg gs://akuc-machine-learning-vertex-ai-pipelines-bucket/crops.csv  gs://akuc-machine-learning-vertex-ai-pipelines-bucket/io-tests/results -r 20 -rm -e thread
  benchmark-multiprocess-local:
    desc: Run benchmark for multiprocess processing and local inputs and outputs
    cmds:
      - benchmarks multithreading IMG_3134.jpeg crops.csv results/ -r 20 -rm -e process
  benchmark-multiprocess-remote:
    desc: Run benchmark for multiprocess processing and remote inputs and outputs
    cmds:
      - benchmarks multithreading gs://akuc-machine-learning-vertex-ai-pipelines-bucket/IMG_3134.jpeg gs://akuc-machine-learning-vertex-ai-pipelines-bucket/crops.csv  gs://akuc-machine-learning-vertex-ai-pipelines-bucket/io-tests/results -r 20 -rm -e process
  plot-all-local:
    desc: Plot all local results
    cmds:
      - benchmarks plot-logs "./*local.log" -p all-local.png
  benchmark-and-plot-all-local:
    desc: Run all benchmarks for local inputs and outputs
    cmds:
      - benchmarks serial IMG_3134.jpeg crops.csv results/ -r 20 -rm
      - benchmarks asynchronous IMG_3134.jpeg crops.csv results/ -r 20 -rm
      - benchmarks multithreading IMG_3134.jpeg crops.csv results/ -r 20 -rm -e thread
      - benchmarks multithreading IMG_3134.jpeg crops.csv results/ -r 20 -rm -e process
      - benchmarks plot-logs "./*local.log" -p all-local.png
  benchmark-and-plot-all-remote:
    desc: Run all benchmarks for remote inputs and outputs
    cmds:
      - benchmarks serial gs://akuc-machine-learning-vertex-ai-pipelines-bucket/IMG_3134.jpeg gs://akuc-machine-learning-vertex-ai-pipelines-bucket/crops.csv  gs://akuc-machine-learning-vertex-ai-pipelines-bucket/io-tests/results -r 5 -rm
      - benchmarks asynchronous gs://akuc-machine-learning-vertex-ai-pipelines-bucket/IMG_3134.jpeg gs://akuc-machine-learning-vertex-ai-pipelines-bucket/crops.csv  gs://akuc-machine-learning-vertex-ai-pipelines-bucket/io-tests/results -r 10 -rm
      - benchmarks multithreading gs://akuc-machine-learning-vertex-ai-pipelines-bucket/IMG_3134.jpeg gs://akuc-machine-learning-vertex-ai-pipelines-bucket/crops.csv  gs://akuc-machine-learning-vertex-ai-pipelines-bucket/io-tests/results -r 10 -rm -e thread
      - benchmarks multithreading gs://akuc-machine-learning-vertex-ai-pipelines-bucket/IMG_3134.jpeg gs://akuc-machine-learning-vertex-ai-pipelines-bucket/crops.csv  gs://akuc-machine-learning-vertex-ai-pipelines-bucket/io-tests/results -r 10 -rm -e process
      - benchmarks plot-logs "./*remote.log" -p all-remote.png
